###START WITH T3

## Welcome to NumPy

## Practice Sheet

* Topic 1: NumPy Arrays -  - Creation from Objects like Lists
    - Installation, Import
    - Creation of Numpy Arrays from Objects like lists

* Topic 2: NumPy Arrays
    - Built-in Methods: arange(), zeros(), ones(), linspace(), eye(), rand(), randn(), randint(), seed(), reshape(), max(), min(), argmax(), argmin(), shape(), dtype()
    
* Topic 3: NumPy Indexing and Selection
    - Sequencing, Slicing, Broadcasting, 2D Array Indexing, Conditional Selection

*  Topic 4: NumPy Operations
    - Arithmetic, ufuncs (Universal Array Funcions), Summary Statistics, Axis logic, 
        
* Documentation at: https://numpy.org/doc/stable/user/


Let's begin by explaining the basics of NumPy

### T1 - NumPy Arrays - Creation from Objects like Lists

#### Basic Overview
* Numpy known as a very useful linear algebra library in Python
* Why Numpy is useful?
    - Almost all libraries in <a href='https://pydata.org/'>PyData</a> ecosystem (pandas, scipy, scikit-learn, etc.) rely on NumPy as one of their main building blocks
    - Incredibly fast because of binding to C libraries
    - Refer to  [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists)
	--The difference is mostly due to "indirectness" -- a Python list is an array of pointers to Python objects, at least 4 bytes per pointer plus 16 	  bytes for even the smallest Python object (4 for type pointer, 4 for reference count, 4 for value -- and the memory allocators rounds up to 16). A 	  NumPy array is an array of uniform values -- single-precision numbers takes 4 bytes each, double-precision ones, 8 bytes. Less flexible, but you 	  pay substantially for the flexibility of standard Python lists!
    
* Use import numpy  or  import numpy as np  to import it as a library

#### NumPy Arrays
* Numpy will be mainly used in the form of NumPy Arrays
* NumPy Arrays are preferable over Lists in Python. Has two types:
    - Vectors and Matrices
    * Vectors are strictly 1-dimensional (1D) arrays 
    * and matrices are 2D 
    * However, matrix can also have only one row or one column
 
#### Why NumPy Arrays over Lists in Python

* Below are the key reasons for using Numpy array instead of a "standard" python list object:
    - Memory Efficiency of Numpy Array vs list
    - Easily expands to N-dimensional objects
    - Speed of calculations of numpy array
    - Broadcasting operations and functions with numpy
    - All the data science and machine learning libraries we use are built with Numpy
    

#### NumPy Installation 

* Already included in the Jupyter environment!

* If not included, install using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. 
    - If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:
        conda install numpy
    
* If not using Anaconda Setup, please refer to [Numpy's official documentation on various installation instructions.](https://www.scipy.org/install.html)




In [1]:
import numpy as np

In [3]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [4]:
np.eye(6)*2

array([[2., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 2., 0., 0.],
       [0., 0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 0., 2.]])

In [6]:
##TEST PROGRAM 1
#Which one is better - Numpy or List
#Create a np1 array using np.arange() for 1 million values
#Create a list1 using range() for 1 million values

#Using %time, In a for loop of range(10)
    #create np2 having elements of np1 multiplied by 3

#Using %time, In a for loop of range(10)
    #create list2 having elements of list1 multiplied by 3

In [7]:
np1 = np.arange(1,1000001)

In [8]:
np1

array([      1,       2,       3, ...,  999998,  999999, 1000000])

In [9]:
print(np1, type(np1), len(np1), sep='\n')

[      1       2       3 ...  999998  999999 1000000]
<class 'numpy.ndarray'>
1000000


In [10]:
l1 = list(range(1,1000001))

In [11]:
print(type(l1), len(l1), sep = '\n')

<class 'list'>
1000000


In [12]:
%time for i in range(10) : np2 = np1*2

Wall time: 24.9 ms


In [13]:
%time for i in range(10) : np2 = np1*2
    
print("*"*20)

%time for i in range(10) : l2 = {item*2 for item in l1}

Wall time: 26.9 ms
********************
Wall time: 2.44 s


In [8]:
l1 = [1,2,3]

np_arr1 = np.ndarray(l1)

In [9]:
np_arr1

array([[[2., 2., 2.],
        [2., 2., 2.]]])

In [10]:
np_arr1 = np.array([1,2,3])

np_arr2 = np.array(l1)


In [11]:
np_arr1

array([1, 2, 3])

In [12]:
np_arr2

array([1, 2, 3])

In [13]:
l1 = [1,2,3]
l2 = [7, 8, 9]
l3 = ['a', 'b', 'c']

my_matrix1 = [l1, l2, l3]

In [14]:
l1 = [[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19]]

In [15]:
np2 = np.array(l1)

In [16]:
type(np2)

numpy.ndarray

In [17]:
np2

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
np2.shape

(3, 5)

In [25]:
np2.ndim

2

In [26]:
np2.dtype

dtype('int32')

In [18]:
np3 = np.arange(20).reshape(4,5)

In [19]:
type(np3)

numpy.ndarray

In [20]:
np3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [21]:
np3.shape

(4, 5)

In [22]:
np3.ndim

2

In [23]:
np3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
np3.dtype

dtype('int32')

In [25]:
#Create a np array of 3 int values using arange()

np.arange(1,4)

array([1, 2, 3])

In [26]:
np.arange(1.0,4.0)

array([1., 2., 3.])

In [27]:
np.arange(1,4 , dtype=float)

array([1., 2., 3.])

In [28]:
np.arange(3,7)

array([3, 4, 5, 6])

In [29]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [30]:
##Create a 10x10 matrix having values between 0.01 to 1.0
#using np.arange().reshape()

np.arange(1,101).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [31]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [40]:
np.linspace(0.1, 1.0, 100).reshape(10,10)

array([[0.1       , 0.10909091, 0.11818182, 0.12727273, 0.13636364,
        0.14545455, 0.15454545, 0.16363636, 0.17272727, 0.18181818],
       [0.19090909, 0.2       , 0.20909091, 0.21818182, 0.22727273,
        0.23636364, 0.24545455, 0.25454545, 0.26363636, 0.27272727],
       [0.28181818, 0.29090909, 0.3       , 0.30909091, 0.31818182,
        0.32727273, 0.33636364, 0.34545455, 0.35454545, 0.36363636],
       [0.37272727, 0.38181818, 0.39090909, 0.4       , 0.40909091,
        0.41818182, 0.42727273, 0.43636364, 0.44545455, 0.45454545],
       [0.46363636, 0.47272727, 0.48181818, 0.49090909, 0.5       ,
        0.50909091, 0.51818182, 0.52727273, 0.53636364, 0.54545455],
       [0.55454545, 0.56363636, 0.57272727, 0.58181818, 0.59090909,
        0.6       , 0.60909091, 0.61818182, 0.62727273, 0.63636364],
       [0.64545455, 0.65454545, 0.66363636, 0.67272727, 0.68181818,
        0.69090909, 0.7       , 0.70909091, 0.71818182, 0.72727273],
       [0.73636364, 0.74545455, 0.7545454

In [41]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [42]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [43]:
np.linspace(1,10,10, endpoint = False)

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [44]:
np.linspace(1,10,11)

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

In [45]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
np.zeros(25).reshape(5,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.ones((3,3), dtype = 'int')


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [48]:
np.ones((3,3))*5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [49]:
np.eye(3)  #eye by default creates diagonal 1 matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
np.eye(3)*5

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

### numpy methods

In [51]:
# to generate random number
import numpy as np
np.random.rand()

0.6147755483384967

In [36]:
np.random.rand()

0.29314279494154183

In [52]:
np.random.rand(3)

array([0.00310769, 0.29199664, 0.76966969])

In [37]:
np.random.rand(100)

array([0.00689058, 0.78507238, 0.55388948, 0.56623049, 0.18381617,
       0.31671069, 0.51305713, 0.57765999, 0.25555225, 0.60761902,
       0.79577627, 0.30510054, 0.49645959, 0.51849542, 0.37612947,
       0.01830224, 0.95918486, 0.14084386, 0.10829881, 0.5874754 ,
       0.06954644, 0.66458975, 0.02049887, 0.13756206, 0.05254295,
       0.87406556, 0.58978597, 0.96450486, 0.42321298, 0.32923787,
       0.54096728, 0.96675132, 0.95242553, 0.08015673, 0.74444799,
       0.69221885, 0.53833927, 0.42556472, 0.09350033, 0.71744265,
       0.24166912, 0.74958451, 0.81495806, 0.98293686, 0.83824323,
       0.1716336 , 0.01779112, 0.09035185, 0.87065131, 0.85454545,
       0.86717319, 0.894516  , 0.67921667, 0.83410795, 0.69000909,
       0.57613786, 0.39475393, 0.22338636, 0.61708118, 0.25575589,
       0.30635247, 0.25748648, 0.657153  , 0.56588426, 0.93267793,
       0.96991208, 0.65212032, 0.13774695, 0.34726604, 0.70497388,
       0.46550482, 0.48762462, 0.97383274, 0.11194907, 0.28320

In [38]:
#take user input for rows and cols
#generate a 2D array of random numbers

r = int(input('Rows: '))
c = int(input('Cols: '))

np.random.rand(r,c)

Rows: 2
Cols: 3


array([[0.79460824, 0.3076323 , 0.64334212],
       [0.7098096 , 0.5183581 , 0.46171051]])

In [39]:
a = np.random.rand(3)

In [40]:
a.shape

(3,)

In [41]:
a

array([0.99608535, 0.09545798, 0.52173896])

### randn - random of normal distribution

In [57]:
np.random.randn()

-0.5757412577169772

In [58]:
np.random.randn(3)

array([-0.02270881, -0.45253091, -0.55831386])

In [44]:
np.random.randn(1,11)

array([[ 0.94111595, -0.42118792,  0.53168379, -0.38872188, -1.41099049,
         1.16787975,  0.84731038,  0.56625651,  1.23375053, -1.30103264,
        -1.90971995]])

In [59]:
r = int(input('Rows: '))
c = int(input('Cols: '))

np.random.randn(r,c)

Rows: 1
Cols: 2


array([[-1.32877229,  0.0906043 ]])

In [45]:
#randint() to generate random integers between start and stop

np.random.randint(1,3,5)

array([2, 2, 1, 2, 2])

In [61]:
np.random.randint(1,99,30)  #generate 30 random integers between 1 and 99

array([ 3, 55, 68, 97,  8, 47, 81, 96, 30, 95, 98, 82, 59, 83, 66, 43, 83,
       98, 64, 51, 46, 76, 29, 68,  1, 26, 96, 43, 68, 35])

In [46]:
np.random.randint(1, 99, 30).reshape(5,6)

array([[10, 90, 56, 76, 77, 84],
       [90, 44,  2, 24, 95, 91],
       [94, 26,  9, 95, 88, 76],
       [87, 44, 86, 22, 47, 34],
       [72, 68, 16, 82, 51,  2]])

In [47]:
np.random.randint(1, 99, (5,6))

array([[80, 81, 61, 81, 44, 62],
       [94, 94,  2,  4, 64, 48],
       [34, 95, 72, 98, 31, 13],
       [23, 73, 35, 88,  6, 35],
       [ 6, 33, 80, 47, 44,  4]])

In [48]:
np.random.seed(99)
np.random.randint(1, 99, (5,6))

array([[ 2, 36, 58, 41, 74, 83],
       [69, 70, 53,  2, 24, 36],
       [56, 66, 49, 94, 60, 88],
       [ 3, 65, 13, 41, 73, 21],
       [60, 40, 80, 48, 28, 63]])

In [49]:
#get max and min values

arr1 = np.random.randint(1,99, (5,6))
print(arr1)
print(arr1.max(), arr1.min(), sep = '<-->')

[[63 18 74 33 22 42]
 [20 23 27 51 60  6]
 [13 97 54 92  2 45]
 [76 12 94 96 42 34]
 [13 78 77 89 74 12]]
97<-->2


In [66]:
print(arr1.argmax(), arr1.argmin(), sep='<===>')   #states the index position of the max and min value in the array.

13<===>16


In [51]:
np.random.seed(10)
arr1 = np.arange(9,99,4)
print(arr1)



[ 9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93 97]


In [53]:
print(arr1[:1])

[9]


In [54]:
arr1 = np.random.randint(9,99, (4,4))
print(arr1)

[[18 24 73 37]
 [98 38 17 82]
 [ 9 49 45 25]
 [20 63 97 71]]


In [55]:
arr1[2:,2:]  #last 2 column values of 3rd and 4th row

array([[45, 25],
       [97, 71]])

In [56]:
arr1[:2,:2]

array([[18, 24],
       [98, 38]])

In [57]:
arr1[:2]

array([[18, 24, 73, 37],
       [98, 38, 17, 82]])

In [60]:
arr1[:2,2:]   #row , column  [start:stop, start,stop]

array([[73, 37],
       [17, 82]])

In [61]:
arr1[2:,:2]

array([[ 9, 49],
       [20, 63]])

In [58]:
arr1[:-3]

array([[18, 24, 73, 37]])

In [59]:
arr1[:]

array([[18, 24, 73, 37],
       [98, 38, 17, 82],
       [ 9, 49, 45, 25],
       [20, 63, 97, 71]])

In [62]:
arr1[::2,0:]

array([[18, 24, 73, 37],
       [ 9, 49, 45, 25]])

In [63]:
arr1[::2, 1::2]

array([[24, 37],
       [49, 25]])

In [64]:
arr1[::2, 1::2] = -199

In [65]:
arr1

array([[  18, -199,   73, -199],
       [  98,   38,   17,   82],
       [   9, -199,   45, -199],
       [  20,   63,   97,   71]])

In [66]:
type(arr1)

numpy.ndarray

In [74]:
arr1 = np.arange(1, 12)
l1 = list(range(1,12))
print(arr1)
print(l1)

[ 1  2  3  4  5  6  7  8  9 10 11]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [75]:
arr1[3:6] = -100
arr1     #numpy array replaces each value with -100

array([   1,    2,    3, -100, -100, -100,    7,    8,    9,   10,   11])

In [76]:
l1[3:6]

[4, 5, 6]

In [73]:
l1[3:6] = [-100]    #list substitutes that slice with -100
l1

[1, 2, 3, -100, 7, 8, 9, 10, 11]

In [78]:
l1[0] = 35353

In [79]:
l1

[35353, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [87]:
arr1 = np.arange(1,12)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [85]:
# arr1 = 99

In [88]:
arr1[:] = 99
arr1

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [89]:
arr1 = np.random.randint(9,99,30)
arr1

array([24, 27, 89, 80, 97, 20, 26, 55, 16, 84, 37, 42, 93, 97, 53, 14, 13,
       80, 97, 97, 59, 63, 43, 24, 86, 97, 24, 15, 94, 31])

In [83]:
arr2 = arr1%3

In [84]:
arr2

array([0, 0, 0, 1, 0, 0, 2, 0, 1, 1, 1, 2, 0, 0, 2, 0, 2, 1, 0, 0, 0, 0,
       2, 1, 2, 2, 1, 2, 1, 0], dtype=int32)

In [90]:
a= []

for i in arr1:
    if i%3 == 0:
        a.append(i)
print(a)

[24, 27, 84, 42, 93, 63, 24, 24, 15]


### numpy array of random integers divisible by 3

In [91]:
import numpy as np

In [ ]:
arr1[arr1%3 == 0]

In [68]:
#Create a numpy array using randint(9,999, (5,6))
#Fetch those values divisible by 7

print((np.random.randint(9,999, (5,6))) % 3)

[[1 2 2 2 0 0]
 [0 1 1 1 1 2]
 [2 1 1 1 1 1]
 [0 2 0 2 2 2]
 [0 2 0 2 1 2]]


In [69]:
arr1 = np.random.randint(9,999, (5,6))

In [70]:
arr1

array([[209, 877, 983, 698, 700,  63],
       [ 86, 462,  22, 764, 418, 391],
       [662, 869, 351, 807, 679,  98],
       [661, 330, 552, 834, 813, 292],
       [539, 102,  86, 415, 928, 615]])

In [71]:
arr1[arr1%7 == 0]

array([700,  63, 462, 679,  98, 539])

In [79]:
arr1[arr1%7 | arr1%5 == 0]  

array([700])

In [80]:
arr1[(arr1%7 == 0) | (arr1%5 == 0)]

array([700,  63, 462, 679,  98, 330, 539, 415, 615])

In [81]:
arr1[(arr1%7 == 0) & (arr1%5 == 0)]

array([700])

In [82]:
arr4 = np.arange(0,11)

In [83]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
arr4*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [85]:
arr4/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [86]:
arr4**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [87]:
arr4 * arr4

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [88]:
arr4 ** arr4

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408], dtype=int32)

In [89]:
arr4+arr4

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [90]:
arr4-arr4

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [91]:
arr4/arr4

<ipython-input-91-b03270b0b3a8>:1: RuntimeWarning: invalid value encountered in true_divide
  arr4/arr4


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [92]:
1/arr4

<ipython-input-92-11d709e4f6a1>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr4


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

### unary functions

In [93]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
np.mean(arr4)

5.0

In [101]:
np.median(arr4)

5.0

In [102]:
np.std(arr4)

3.1622776601683795

In [103]:
np.exp(arr4)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [104]:
np.sin(arr4)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [105]:
np.cos(arr4)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [106]:
np.tan(arr4)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])

In [107]:
arr_2d = np.array([[1,2,3,4], [11,12,13,14], [111,222,333,444]])

In [109]:
arr_2d

array([[  1,   2,   3,   4],
       [ 11,  12,  13,  14],
       [111, 222, 333, 444]])

In [110]:
np.sum(arr_2d)

1170

In [111]:
np.sum(arr_2d, axis = 0)  #columnar addition

array([123, 236, 349, 462])

In [113]:
np.sum(arr_2d, axis = 1)  #row addition

array([  10,   50, 1110])

In [114]:
np.mean(arr_2d, axis = 0)  #column wise mean

array([ 41.        ,  78.66666667, 116.33333333, 154.        ])

In [2]:
np.mean(arr_2d, axis = 1)  #row wise mean

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [4]:
np.rand

AttributeError: module 'numpy' has no attribute 'rand'

In [5]:
import numpy as np

a = np.array([0,1,2,3])

print(a.shape)



(4,)


In [6]:
print(a)

[0 1 2 3]
