## Basic Operators

In [1]:
print("2==2 is {}".format(2==2))

2==2 is True


In [2]:
print(f"2!=2 is {2!=2}")

2!=2 is False


In [4]:
print(f"2>3 is {2>3}")

2>3 is False


In [5]:
print(f"2<3 is {2<3}")

2<3 is True


In [6]:
print(f"2>=2 is {2>=2}")

2>=2 is True


In [7]:
print(f"2<=-2 is {2<=-2}")

2<=-2 is False


## Chained comparison operators

In [8]:
print(f"1<=2<=3 is {1<=2<=3}")

1<=2<=3 is True


In [9]:
print(f"1<=2 and 2<=3 is {1<=2 and 2<=3}")

1<=2 and 2<=3 is True


In [10]:
print(f"1<=2 and 2>=3 is {1<=2 and 2>=3}")

1<=2 and 2>=3 is False


In [11]:
print(f"1<=2 and not(2>=3) is {1<=2 and not(2>=3)}")

1<=2 and not(2>=3) is True


In [12]:
print(f"1<=2 or 2>=3 is {1<=2 or 2>=3}")

1<=2 or 2>=3 is True


In [13]:
0 == 100

False

In [14]:
-1 == -1.0

True

In [15]:
-1 == -2/2.0

True

In [16]:
0==100 or -1==-1.0

True

In [17]:
0==100 and -1 == -1.0

False

# Welcome to CO2 - Comparison Operators, Statements, Methods & Functions

## CLASS DISCUSSION

### Topic 2: if-elif-else Statement & while loop

* In this session, we are going to focus on the following
    - Conditional Statements (If-elif-else)
    - While Loop 

* Sample Problem Statement:  If x > y then print x else print y
* Python code structure
    - if x>y :
        - print(x)
     - else:
        - print(y)

* The if, for, while statements/ conditions end with a colon, and whitespace is used (indentation) to describe what takes place in case of the statement or within that loop.

In [20]:
#By default if statement considers True

if False:
    print('This is false')
else:
    print('This is True')

This is True


In [22]:
if True:
    print('This is Truee')
else:
    print('This is False')

This is Truee


In [36]:
loc = input('Enter your current location (Market or Movie or College or Playground: ').title()

if loc == 'Market':
	print('Please bring fruits from {}'.format(loc))
elif loc == 'Movie':
	print('Enjoy the movie'.format(loc))
elif loc == 'Playground':
	print('Have fun on the {}'.format(loc))
elif loc == 'College':
	print('Return to {} on 6pm'.format(loc))
else:
	print('reach home asap')

Enter your current location (Market or Movie or College or Playground: college
Return to College on 6pm


In [3]:
for val in range(3):
    loc = input('Enter your current location (Market or Movie or College or Playground: ').title()
    
    if loc == 'Market':
        print(f'Please bring fruits from {loc}')
    elif loc == 'Movie':
        print('Enjoy the movie'.format(loc))
    elif loc == 'Playground':
        print('Have fun on the {}'.format(loc))
    elif loc == 'College':
        print('Return to {} on 6pm'.format(loc))
    else:
        print('reach home asap')



Enter your current location (Market or Movie or College or Playground: market
Please bring fruits from Market
Enter your current location (Market or Movie or College or Playground: movie
Enjoy the movie
Enter your current location (Market or Movie or College or Playground: college
Return to College on 6pm


### T2.2 - while loop

* A while statement executes a single/group of statements as long as the condition is true. 
    - break statement is used within the while loop to exit the innermost loop for a specific situation. Breaks out of the    current closest enclosing loop.
    - continue statement is used within the while loop to skip the operation or processing for a particular scenario. Goes to 
      the top of the closest enclosing loop.
    - pass: Does nothing at all. AVoid getting an error while setting up the placeholder for while or if or for 
      statements/loops

* The general format of a while loop is:

* while test:
    - code statements
* else:
    - final code statements

In [4]:
for val in range(3):
    loc = input('Enter your current location (Market or Movie or College or Playground: ').title()
    
    if loc == 'Market':
        print('Please bring fruits from {}'.format(loc))
    elif loc == 'Movie':
        continue
        print('Enjoy the movie'.format(loc))
    elif loc == 'Playground':
        print('Have fun on the {}'.format(loc))
    elif loc == 'College':
        print('Return to {} on 6pm'.format(loc))
    else:
        print('reach home asap')


Enter your current location (Market or Movie or College or Playground: market
Please bring fruits from Market
Enter your current location (Market or Movie or College or Playground: movie
Enter your current location (Market or Movie or College or Playground: college
Return to College on 6pm


### Continue skips the particular iteration and goes to the beginnning of the loop

In [5]:
for val in range(3):
    loc = input('Enter your current location (Market or Movie or College or Playground: ').title()
    
    if loc == 'Market':
        print('Please bring fruits from {}'.format(loc))
    elif loc == 'Movie':
        continue
        print('Enjoy the movie'.format(loc))
    elif loc == 'Playground':
        print('Have fun on the {}'.format(loc))
    elif loc == 'College':
        break
        print('Return to {} on 6pm'.format(loc))
    else:
        print('reach home asap')


Enter your current location (Market or Movie or College or Playground: market
Please bring fruits from Market
Enter your current location (Market or Movie or College or Playground: college


### break - exits out of the loop and terminates it

In [6]:
for val in range(3):
    loc = input('Enter your current location (Market or Movie or College or Playground: ').title()
    
    if loc == 'Market':
        pass
        print('Please bring fruits from {}'.format(loc))
    elif loc == 'Movie':
        continue
        print('Enjoy the movie'.format(loc))
    elif loc == 'Playground':
        print('Have fun on the {}'.format(loc))
    elif loc == 'College':
        break
        print('Return to {} on 6pm'.format(loc))
    else:
        print('reach home asap')


Enter your current location (Market or Movie or College or Playground: market
Please bring fruits from Market
Enter your current location (Market or Movie or College or Playground: haha
reach home asap
Enter your current location (Market or Movie or College or Playground: college


In [43]:
str1 = 'A1%%%B1%%C1%%%D1'
split_val = '%%'


In [44]:
str1.split(split_val)

['A1', '%B1', 'C1', '%D1']

In [2]:
import numpy as np
myList = np.arange(1,19,2).reshape(3,3)

In [3]:
myList

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [4]:
arr2 = np.array(myList)

In [5]:
print(arr2)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


In [6]:
arr2

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [50]:
import numpy as np
arr1 = np.array([1,2,3,5,8])
arr1 = arr1 + 1

In [51]:
arr1

array([2, 3, 4, 6, 9])

In [52]:
t1 = (10,20,40,30,80,90)
dict1 = {t1[i]:t1[i]**2 for i in range(0,len(t1),2)}

In [53]:
dict1


{10: 100, 40: 1600, 80: 6400}

In [54]:
str1 = '22FEB2024'
print(str1[-6::2],str1[-6::-2],sep='&')

E22&E2


In [55]:
t1 = (100,50,0,-50,100,0)

In [56]:
t2 = (100,51,-50,0)

In [57]:
print(len(set(t1+t2)))

5


In [58]:
t1+t2

(100, 50, 0, -50, 100, 0, 100, 51, -50, 0)

### question done on 29 feb 2024

### Q3) parse the string char-wise and print each char in reverse order

### 1- get user input
### 2- print each char of string in reverse order

In [21]:
a = input('Enter string: ')

b = list(a)
print(b[::-1])

Enter string: Hello World
['d', 'l', 'r', 'o', 'W', ' ', 'o', 'l', 'l', 'e', 'H']


In [22]:
for i in b[::-1]:
    print(i,end='')

dlroW olleH

In [23]:
str1 = input('Enter string: ')
list1 = str1.split(" ")

for val in list1[::-1]:
    print(val,end="")

Enter string: Hello World
WorldHello

In [24]:
### Q4) Dictionary - Count voewls in a string

### Q4) Take string as user input
### - count the occurence of each vowel in that string
### - display dictionary with vowel name and count in the string

In [49]:
vowel = ['a','e','i','o','u']

user = input('Enter String: ')

dict1 = {vowel[i]:user.count(vowel[vowel.index(i)]) for i in vowel}

Enter String: hekko


TypeError: list indices must be integers or slices, not str

In [7]:
vowel = ['a','e','i','o','u']

user = input('Enter String: ')

dict1 = {i: user.count(i) for i in vowel}
print(dict1)

Enter String: wolf of the wall street
{'a': 1, 'e': 3, 'i': 0, 'o': 2, 'u': 0}


In [36]:
vowel = ['a','e','i','o','u']
user = input('Enter String: ')

Enter String: aapplee


In [37]:
user.count('a')

2

In [41]:

vowel[0]

'a'

In [48]:
vowel.index('e')

1

In [42]:
str1 = input('String: ')

list1 = list(str1)

dict1 = {'a':0, 'e':0, 'i':0, 'o':0, 'u':0}

for item in list1:
    if 

KeyboardInterrupt: Interrupted by user

In [9]:
myvar = 0

while myvar<=3:
    print('my var is now: ',myvar)
    myvar += 1

my var is now:  0
my var is now:  1
my var is now:  2
my var is now:  3


In [52]:
myvar = 0

while True:
    print('myvar is now: ', myvar)
    myvar += 1
    if myvar%7 == 0:
        break

myvar is now:  0
myvar is now:  1
myvar is now:  2
myvar is now:  3
myvar is now:  4
myvar is now:  5
myvar is now:  6


In [54]:
#no output

myvar = 0

while True:
    if myvar%7 ==0:
        break
    print('myvar is now: ', myvar)
    myvar += 1

In [56]:
list1 = [0,1,2,3,4,5,6,7,8,9]

for val in list1:
    print(val)

0
1
2
3
4
5
6
7
8
9


In [58]:
list1 = [0,1,2,3,4,5,6,7,8,9]

for val in list1:
    if val%2 != 0:
        print(val)

1
3
5
7
9


In [60]:
list1 = [0,1,2,3,4,5,6,7,8,9]

for val in list1:
    if val%2 == 0:
        print(val)

0
2
4
6
8


In [61]:
for val in list1[1::2]:
    print(val)

1
3
5
7
9


In [62]:
for val in list1[0::2]:
    print(val)

0
2
4
6
8


In [77]:
list1 = [0,1,2,3,4,5,6,7,8,9]

for val in list1[1::2]:
    print(val)

print(list1)
newlist1 = list1[val] + list1[val+1]

1
3
5
7
9
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


IndexError: list index out of range

In [72]:
list1[val+1]

IndexError: list index out of range

In [73]:
list1 = [0,1,2,3,4,5,6,7,8,9]

sum = 0
sumE = 0
sumO = 0

for val in list1:
    sum += val
    if val%2 ==0:
        sumE += val
    else:
        sumO += val
        
print(sum, sumE, sumO)

45 20 25


In [ ]:
list1 = [0,1,2,3,4,5,6,7,8,9]

sum = 0
sumE = 0
sumO = 0

for val in list1:
    sum += val
    if val%2 ==0:
        sumE += val
    else:
        sumO += val
        
print(sum, sumE, sumO)