WORKING WITH NUMBERS (INTEGERS and FLOATS)
============================================== 

# Welcome to CO1 - Understanding the Python Basics

## Key Topics:

### 1. Numbers and Variables Assignment
### 2. Strings and Print Formatting
### 3. Lists
### 4. Dictionaries
### 5. Tuples, Sets & Booleans


Name  |  Type  |  Description
|:---------|:------|:--------------------|
Integers|int|Whole numbers like -10, 0, 20, 999
Floating point	|float| Numbers having decimal point like -3.3, 9.99, 9e7
Strings	|str|	Ordered sequence of characters like  "BABD"   'Analytics'   "$199.99" 
Lists	|list|	Ordered Mutable sequence of objects in square brackets like   [10,"hello",200.3]
Dictionaries	|dict|	Unordered & Mutable Key:Value pairs in curly brackets :  {"mykey" : "value" , "name" : "Frankie"}
Tuples	|tup|	Ordered Immutable sequence of objects in round brackets like (10,"hello",200.3)
Sets	|set|	Unordered collection of unique objects (No Duplicates) like  {"a","b"}
Booleans	|bool|	Logical value indicating True or False

## Topic 1: Numbers and Variables Assignment

- ### Numbers - Integers and Floating point
    * ### Integers: -29, 59, 0, 1000
    * ### Floating Point: 2.9, -0.6, 6E9, 2E-3

In [2]:
## Basic Arithmetic Operations

#Addition, Multiplication, Division, Subtraction, Exponential {:.nf}.format

print("3+2 = ", 3+2)

3+2 =  5


In [3]:
print("3+2 =", 3+2)
print("3+3.9 =", 3+3.9)
print("3*3 =",3*3 )
print("3*3.9 =",3*3.9)
print("23/3 =", 23/3)
print("99*9 =" , 99*9)
print("2e9 =", 2e9)  #2*10^9
print("2E-2 =",2E-2) #2*10^-2

3+2 = 5
3+3.9 = 6.9
3*3 = 9
3*3.9 = 11.7
23/3 = 7.666666666666667
99*9 = 891
2e9 = 2000000000.0
2E-2 = 0.02


In [5]:
print("9**2 =", 9**2)

9**2 = 81


In [6]:
var1= 99 + 10 * 9 - 3
print(var1)

186


In [7]:
var2 = 99 + 10 * 9 / 3
print(var2)

129.0


In [8]:
var3= (99 + 10) * 9 - 3
print("var3 = ", var3)

var4 = (99.5 - (10 * 9)) / 3
print("var4 = ", var4)

var3 =  978
var4 =  3.1666666666666665


In [9]:
v1 = 5.5
v2 = 9
v3 = -99
v4 = "Hello"

In [11]:
print(v1,v2,v3,v4, sep =' ')    #separator operator

5.5 9 -99 Hello


In [12]:
print(v1,v2,v3,v4, sep ='|')  #seporator operator

5.5|9|-99|Hello


In [18]:
print(v1,v2,v3,v4, end = "  (:  <>   :) ")    #ending operator
print(v1,v2,v3,v4, sep = '|')


5.5 9 -99 Hello  (:  <>   :) 5.5|9|-99|Hello


#### we can use shift + tab to see the documentation of every class

In [19]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [21]:
a = print(v1,v2,v3,v4, sep = '|', flush = True)

5.5|9|-99|Hello


In [22]:
a

In [26]:
# v111 = 29

# #Write Print statement here to get below output


# v111 = ["India", "USA", "UK"]

# #Write Print statement here to get below output




# Output
# ======
# * Earlier: v111 =  29    Variable Type =  <class 'int'>
# * Now: v111 =  ['India', 'USA', 'UK']    Variable Type =  <class 'list'>

## Format function

In [41]:
v111 = 29

In [42]:
print("Earlier: v111=", v111, "Variable Type=", type(v111))

Earlier: v111= 29 Variable Type= <class 'int'>


In [43]:
tp = type(v111)
print(f"Earlier: v111 = {v111}   Variable Type = {type(v111)}")

Earlier: v111 = 29   Variable Type = <class 'int'>


In [44]:
v111 = ["India", "USA", "UK"]

In [45]:
print(f"Now: v111 = {v111}    Variable Type = {type(v111)}")

Now: v111 = ['India', 'USA', 'UK']    Variable Type = <class 'list'>


In [46]:
print(f"Address of v111 is {id(v111)}")

Address of v111 is 1734781307328


In [48]:
###v111 = 99
###v222 = v111

In [1]:
import numpy as np

In [2]:
np.linspace(1,40,10)

array([ 1.        ,  5.33333333,  9.66666667, 14.        , 18.33333333,
       22.66666667, 27.        , 31.33333333, 35.66666667, 40.        ])

In [4]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [5]:
np.arange(1,40,10)

array([ 1, 11, 21, 31])

In [7]:
np.random.rand(3,2)

array([[0.70094875, 0.191351  ],
       [0.816474  , 0.45597138],
       [0.67086507, 0.31226297]])

In [11]:
np.random.randint(50,size=10)

array([34, 45,  6,  9, 45, 10, 37, 48,  1, 17])

In [14]:
np.random.randn(5)

array([ 1.33718878,  0.80195481, -0.61910019, -0.21813649,  2.21393853])