In [1]:
import numpy as np
#print(np.ones((3,9))*5)
np.zeros((3,9))+5

array([[5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [2]:
print(np.ones((3,9))*5)

[[5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5.]]


In [3]:
import numpy as np
#print(np.random.rand(5,6))
np.random.randint(0, 100, (5,6))/100

array([[0.31, 0.83, 0.18, 0.24, 0.23, 0.04],
       [0.69, 0.34, 0.2 , 0.94, 0.36, 0.94],
       [0.73, 0.29, 0.18, 0.84, 0.16, 0.31],
       [0.27, 0.84, 0.27, 0.39, 0.36, 0.59],
       [0.44, 0.82, 0.57, 0.  , 0.14, 0.96]])

In [5]:
print(np.random.rand(5,6))

[[0.03591049 0.59221971 0.82949165 0.29794556 0.80657605 0.53528623]
 [0.50909635 0.81416996 0.56591114 0.3990406  0.70923379 0.30508084]
 [0.5071655  0.45577706 0.01065364 0.95439289 0.3034009  0.30643257]
 [0.55992359 0.91153659 0.40991798 0.7336022  0.78846671 0.7723645 ]
 [0.04772241 0.71157642 0.49015746 0.76768473 0.107813   0.84828792]]


In [8]:
np.random.randint(0, 100, (5,6))/100

array([[0.5 , 0.75, 0.65, 0.53, 0.78, 0.54],
       [0.15, 0.13, 0.56, 0.91, 0.83, 0.74],
       [0.09, 0.78, 0.87, 0.85, 0.2 , 0.21],
       [0.11, 0.52, 0.9 , 0.78, 0.1 , 0.75],
       [0.94, 0.31, 0.49, 0.92, 0.84, 0.59]])

In [9]:
print(np.random.rand(5,6).reshape(5,6))

[[0.02882545 0.60624682 0.14029912 0.45580793 0.55003263 0.22587705]
 [0.53845835 0.72523597 0.11375528 0.65896193 0.23080097 0.21707394]
 [0.8295972  0.8485421  0.93223695 0.81554567 0.5457178  0.9941691 ]
 [0.7024969  0.52196757 0.37609041 0.71511037 0.473328   0.9943219 ]
 [0.98911651 0.06187461 0.63403229 0.51584455 0.75694845 0.91048981]]


In [10]:
import numpy as np
print(np.random.randint(9, 72, (4,3)))

[[54 16 66]
 [63 20 13]
 [14 36 12]
 [37 10 69]]


In [14]:
np.random.randint(9,72,(4,3))

array([[60, 44, 67],
       [20, 53, 33],
       [25, 22, 35],
       [10, 46, 65]])

In [15]:
np.random.randint(9,72,12).reshape(4,3)

array([[52, 34, 54],
       [39, 60, 68],
       [30, 24, 51],
       [36, 52, 49]])

In [16]:
dict1 = {'name': 'Vinay',
         'age': 18, 
         'gender':'male', 
         'class': 12, 
         'stream':'non-medical'}

In [17]:
dict1

{'name': 'Vinay',
 'age': 18,
 'gender': 'male',
 'class': 12,
 'stream': 'non-medical'}

In [21]:
dict1.pop('age')

18

In [22]:
dict1.popitem()

('stream', 'non-medical')

In [24]:
dict1

{'name': 'Vinay', 'gender': 'male', 'class': 12}

In [25]:
l1 = [1, 3, 5]
l1.append("Hello")
l1.extend("hello2")
l1

[1, 3, 5, 'Hello', 'h', 'e', 'l', 'l', 'o', '2']

In [26]:
arr1D = np.arange(1,10)
print(arr1D)
arr2D = np.arange(1, 10).reshape(3,3)
print(arr2D)
arr2D_1 = np.random.randint(1, 10, (3,3))
print(arr2D_1)
arr2D

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 8]
 [7 2 5]
 [9 6 7]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
list1 = ['AA', 'BBB', 9999]
for item in list1:
   print(item)

AA
BBB
9999


In [ ]:
list2 = ['AA', 'BBB', 'CCCC']
for item in list2:
    list2.append(item.upper())

print(list2)

In [32]:
list2 = ['AA', 'BBB', 'CCCC']
for item in list2:
    list2.append(item.upper())
    print(list2)

['AA', 'BBB', 'CCCC', 'AA']
['AA', 'BBB', 'CCCC', 'AA', 'BBB']
['AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC']
['AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA']
['AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA', 'BBB']
['AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC']
['AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA']
['AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA', 'BBB']
['AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC']
['AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA']
['AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA', 'BBB']
['AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC']
['AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA']
['AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', 'AA', 'BBB', 'CCCC', '

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



KeyboardInterrupt: 

In [30]:
str1 = "02468"
list1 = [val for val in str1 if int(val)%4 == 0]
print(list1)

['0', '4', '8']


In [33]:
str1 = "EVENING"
list1 = [item for item in str1 if item not in "AEIOU"]
print(list1)

['V', 'N', 'N', 'G']


In [34]:
T1 = (1, 6)
T2 = (2, 7)
T1 += (5, 6)
T2[1] = (5, 6)
print(T1)
print(T2)

TypeError: 'tuple' object does not support item assignment

In [35]:
L1 = [1, 6]
L2 = [2, 7]
L1 += [5, 6]
L2[-1] = [5, 6]
print(L1)
print(L2)

[1, 6, 5, 6]
[2, [5, 6]]


In [36]:
str1 = 'PYTHON IS AN INTERESTING LANGUAGE'
str2 = str1[:6]
print(str2[-5::2])

YHN


In [37]:
import numpy as np
arr1=np.array([10,12,14,16,18,20,22])
print(arr1[1:5:2])

[12 16]


In [38]:
import numpy as np
arr1=np.arange(5,50,5)
print(arr1)

[ 5 10 15 20 25 30 35 40 45]


In [39]:
import numpy as np
arr1=np.arange(3,30,3).reshape(3,3)
print(arr1)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [41]:
#Printing unique items 
list1 = [9, 18, 27, 18, 9]
list2 = []

for val in list1:
    if val not in list2:
        list2.append(val)
        
print(list2)

[9, 18, 27]


In [42]:
set1 = {0, 1, 2, 3, 4}
set2 = set()

for item in set1:
    set2.add(item%3)
    
print(set2)

{0, 1, 2}


In [47]:
Dict1 = {11:"Eleven", 10:"Ten", 7:"Seven", 9: "Nine", 1: "One"}
List1 = []
List2 = []

for key, val in Dict1.items():
    if "even" in val:
        List1.append(key)
    
    if "en" in val:
        List2.append(key)
        
print(Dict1.items())
print(List1)
print(List2)

dict_items([(11, 'Eleven'), (10, 'Ten'), (7, 'Seven'), (9, 'Nine'), (1, 'One')])
[11, 7]
[11, 10, 7]


In [44]:
str1 = "PYTHON"
list1 = [0, 60, 70, 80, 90, 100]
dict1 = {}
size = len(list1)

for n in range(size):
    dict1[list1[n]] =str1[n]

print(dict1)

{0: 'P', 60: 'Y', 70: 'T', 80: 'H', 90: 'O', 100: 'N'}


In [48]:
list1 = [-1, 1]
list2 = [-2, 2]
list3 = [-3, 3]
list4 = [-4, 4]

list1.append(list2)
list1.extend(list3)
list1.append(list4)

print(list1)

[-1, 1, [-2, 2], -3, 3, [-4, 4]]


In [49]:
list1 = ['04th', 'March', 'Monday']
for item in list1:
    print(item.upper(), end=" ")

04TH MARCH MONDAY 

In [50]:
my_str1 = '04Mar2024,Monday'
print(my_str1[::-2])

ydo,22a4


In [51]:
my_str = "PyThOn"
my_str[-1] = 'N'
my_str[2] = 't'
print(my_str)

TypeError: 'str' object does not support item assignment

In [52]:
my_tup = (10, 20, [31, 32, 33], 40, 50)

my_tup[2][1] = 100
print(my_tup)

(10, 20, [31, 100, 33], 40, 50)


In [53]:
my_list = [10, 20, (31, 32, 33), 40, 50]

my_list[2][1] = 100
print(my_list)

TypeError: 'tuple' object does not support item assignment

In [54]:
my_list = [10, 20, [31, 33, 35], 40, 50]

my_list[2].extend([99,99,99])
print(my_list)

[10, 20, [31, 33, 35, 99, 99, 99], 40, 50]


In [55]:
my_dict = {}
my_tup = ("APP1", "APP2", "APP3", "APP4", "APP5")

for val in range(6, 1, -1):
    my_dict[val-1] = my_tup[val-2]

print(my_dict)

{5: 'APP5', 4: 'APP4', 3: 'APP3', 2: 'APP2', 1: 'APP1'}


In [56]:
import numpy as np

arr1 = np.array(['One', 'Four', 'THREE'])
list1 = ['one', 'four', 'three']

list1.sort(key=len)

print(np.sort(arr1))
print(list1)

['Four' 'One' 'THREE']
['one', 'four', 'three']


In [57]:
import numpy as np

arr1 = np.array([7, 5, 3, 2, 6, 1, 4])

#Sort the numpy array in ascending order
arr2 = np.sort(arr1)

#Sort the numpy array in descending order
arr3 = arr2[::-1]

print("arr1: ", arr1)

print("arr2: ", arr2)

print("arr3: ", arr3)

arr1:  [7 5 3 2 6 1 4]
arr2:  [1 2 3 4 5 6 7]
arr3:  [7 6 5 4 3 2 1]


In [58]:
myVal = 0

while True:
    if myVal == 0:
        myVal += 1
        continue
    
    if myVal%3 == 0:
        break
     
    print('myVal: ',myVal)
    myVal += 1

print("Hello")

myVal:  1
myVal:  2
Hello


In [59]:
list1 = [10, 20, 30, 40]

list1.append((50, 60, 70))
print(len(list1))

5


In [60]:
t1 = (1, 2, 3, 2, 3, 4, 2, 2, 2)

print(t1.count(2))
print(t1.index(3))

5
2


In [61]:
import numpy as np

arr1 = np.arange(9, 99, 10)
arr1 = arr1 - 9
print(arr1)

[ 0 10 20 30 40 50 60 70 80]


In [62]:
arr1 = np.arange(10) 
print(arr1[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [63]:
import numpy as np
np.random.randint(9, 3)

ValueError: low >= high